### ISSUE TITLE
Remove cover plate from Tony

### ISSUE THREAD

**Issue by Hazling** [toniebox-reverse-engineering/toniebox#20]
Hey guys,

I just wanted to add the extension SD Card cable to my box. I am already struggeling with the first step. In the speedrun Video I saw on Youtube, that the cover plate that covers the screws is simply removed with a hard knock on the bottom side of the box where the cover is attached. Afterwards it could easily be removed. I have tried that now for a while but it does not work. Is there any hint for that procedure? I would really appreciate any help :)
Best regards,
Hazling

**Comment by Hazling** [comment]
Hey, I have just found another video in the forum! It worked and I am going on :)
Br, Hazling

**Comment by Gummibeer** [comment]
A link to the video that solved your issue would be appreciated.

**Comment by Hazling** [comment]
Here we go:

https://youtu.be/Cv9ID4-P6_A?si=vBRl_KVLRe-PoLt9
