### ISSUE TITLE
firmware_info.py: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by AlbrechtL** [toniebox-reverse-engineering/toniebox#5]
When running `firmware_info.py` I got the following error. 

```
Firmware Version: 	EU_V3.0.7-0
Firmware Version: 	EU_V3.0.7_stable_branch
Traceback (most recent call last):
  File "./firmware_info.py", line 165, in <module>
    main(sys.argv[1:])
  File "./firmware_info.py", line 161, in main
    printAllInfo(data)
  File "./firmware_info.py", line 43, in printAllInfo
    print("\nCreation Date: \t\t" + findCreationDate(data))
  File "./firmware_info.py", line 65, in findCreationDate
    return data[-152:-140].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by SciLor** [comment]
@elektrischermoench

**Comment by elektrischermoench** [comment]
Running with an complete Firmware-Dump read with **cc3200tool -read_flash** is not supported at the moment but I will add it as an feature and add proper exception handling to the python file.

**Comment by elektrischermoench** [comment]
I would suggest to close this issue. The script is now dealing with exception in a proper way. And the flash dump files read out with cc3200tool aren't supported. You can only parse files read out with -read_flash option.
